### ISSUE TITLE
Bug: yearly month: (1<) day: {day_of_week:  []}

### ISSUE THREAD

**Issue by leon971** [rossta/montrose#105]
```
Montrose.yearly(month: 1, day: {friday: [2]} ).events.take(1)
 => [Fri, 10 Jan 2020 20:20:16 EET +02:00]
```
This example works.
But if month greater than one, it goes forever loop, for example:
`Montrose.yearly(month: 2, day: {friday: [2]} ).events.take(1)`

**Comment by rossta** [comment]
Thanks for the report!
