### ISSUE TITLE
Possible to have occurrences at different times on different days?

### ISSUE THREAD

**Issue by adambedford** [rossta/montrose#111]
Is it possible to configure a series to have occurrences at different times on different days? e.g. a single `Recurrence` with events every week on Tuesday at 6pm and Thursday at 8pm?

**Comment by rossta** [comment]
Currently, the way to do this would be to build a schedule of multiple recurrences and enumerate the merged results: 

https://github.com/rossta/montrose/blob/91af7d2d5c337aa255510179d24eb023775674bb/lib/montrose/schedule.rb#L13-L28

https://github.com/rossta/montrose/blob/91af7d2d5c337aa255510179d24eb023775674bb/lib/montrose/schedule.rb#L62-L70

**Comment by adambedford** [comment]
Thank you for the guidance. Will this still play nicely with `to_h` and
marshaling the recurrence to a DB field?

**Comment by rossta** [comment]
Not currently but I'd welcome patches to add support for those features!

**Comment by rossta** [comment]
Added support for `Schedule#load` and `Schedule#dump` in `0.10.1`
