### ISSUE TITLE
wrong times with travel_to in testing

### ISSUE THREAD

**Issue by krtschmr** [rossta/montrose#112]
i'm writing tests and i'm using `travel_to` to ensure things are happening in the future

i start with a ruleset every day at 6.00.00 UTC
` => #<Montrose::Recurrence:2abfbe9aa8c8 {:every=>:day, :at=>[[6, 0, 0]]}>` 

`Time.now` is returning me `2019-07-15 04:00:11 +0000`

the next execution is today at 6, which is correct
    buy.schedule.events.first
    => Mon, 15 Jul 2019 06:00:00 UTC +00:00

we travel now into the future

    travel_to 3.hours.from_now
    => nil
    Time.now
    => 2019-07-15 07:01:54 +0000
    buy.schedule.events.first
    => Mon, 15 Jul 2019 06:00:00 UTC +00:00

why is that?

**Comment by krtschmr** [comment]
i start to believe this gem should not be used in production if we need to rely on correct data.

```
pry(main)> Time.now
=> 2019-07-15 04:24:50 +0000
pry(main)> Montrose.daily.at( "13:00" ).events.next
=> Mon, 15 Jul 2019 13:00:00 UTC +00:00
pry(main)> Montrose.daily.at( "3:00" ).events.next
=> Mon, 15 Jul 2019 03:00:00 UTC +00:00
```

i don't think this is a correct expectation

**Comment by rossta** [comment]
The daily recurrence starts on the day of the current time regardless of the current time as designed. 

Dealing with a recurring time semantics is hard so if the gem doesn't do what you expect, feel free to submit a PR.

**Comment by krtschmr** [comment]
well, i think that an event, that already is in the past, should never be the next event.  i checked ice_cube, works perfect for that case.

**Comment by rossta** [comment]
I'll consider changing this behavior. Thanks for the report.
