### ISSUE TITLE
Question on Recurrence#between

### ISSUE THREAD

**Issue by mmagn** [rossta/montrose#118]
Hi, me again :)

I have noticed a strange behaviour with between option in Recurrence and I need your help:

```ruby
starts = Date.new(2019, 7, 15)

Montrose.daily(starts: starts, total: 1).to_a
=> [2019-07-15 00:00:00 +0200] # OK

between_range = Date.new(2019, 7, 22)..Date.new(2019, 7, 28)
Montrose.daily(starts: starts, total: 1).between(between_range).to_a
=> [2019-07-23 00:00:00 +0200] # ??
```
For the last result I was expected an empty array because the only occurrence is not in the between range.

Am I missing something?

Thanks for your help.

**Comment by rossta** [comment]
The logic for `between` will change the effective start time so the given `starts` is effectively ignored. It's meant to be a shorthand for separate `starts` and `until` options. Using both `starts` and `between` shouldn't be necessary. Do you have a use case for that?

**Comment by mmagn** [comment]
Yes, here is the case :

I'm building an app with a calendar feature.
The user can create many events with recurrence, one of them can be :
An event starting on 10th july 2019, repeating each week for a total of 4 times.

My app also displays the calendar with the planned events (fullcalendar.io).
The calendar displays events by week, and to get only the events needed for the week it queries an api endpoint `/events` with params `start` and `end`.

To know if an event should be include in query's result I tried this way :
```ruby
event.recurrence.between(date_range_params).map do |occurence|
  ... # return an occurence of the event
end
```

With the example I used at the beginning (event starting on 10th july 2019, repeating each week for a total of 4 times):
The 4 occurences of the event should exist on : 10th july 2019, 17th july, 24th july and 31th july.

```ruby
Montrose.every(:week, starts: Date.new(2019, 7, 10), total: 4).to_a
=> [2019-07-10 00:00:00 +0200, 2019-07-17 00:00:00 +0200, 2019-07-24 00:00:00 +0200, 2019-07-31 00:00:00 +0200] # Ok
```

So when the calendar asks the api for occurences of this event during the week of 2nd september 2019 to 10th september 2019, I was expecting to not get any occurence of the event, but this is not result.
```ruby
Montrose.every(:week, starts: Date.new(2019, 7, 10), total: 4).between(Date.new(2019, 9, 1)...Date.new(2019, 9, 8)).to_a
=> [2019-09-04 00:00:00 +0200]
```

At the beginning I thought between was a shortcut for `starts:` and `until:` but I was fooled by the fact that when `between` option is set, `until` is automatically set, but `starts` is untouched:
```ruby
Montrose.every(:week, starts: Date.new(2019, 7, 10), total: 4).between(Date.new(2019, 9, 1)...Date.new(2019, 9, 8)).as_json
=> {"every"=>"week", "starts"=>"2019-07-10T00:00:00.000+02:00", "until"=>"2019-09-08T00:00:00.000+02:00", "between"=>"2019-09-01...2019-09-08", "total"=>4}
```

For the moment I solved my problem in my code by filtering the array of occurences :
```ruby
event.recurrence.until(end_param).select { |o| o >= start_param }.map do |occurence|
  ...
end
```
Do you see an other way to do it with Montrose ?

**Comment by rossta** [comment]
Ah, I see. What you want is the _intersection_ of two sets events, so you can just use Ruby.

One way would be as follows:
```ruby
recurrence = Montrose.every(:week, starts: Date.new(2019, 7, 10), total: 4)
range = Date.new(2019, 9, 1)...Date.new(2019, 9, 8)
recurrence.to_a & range.to_a
# => []
```

Alternatively, you could `select` over the recurrence and use `Range#include?` to filter the results:
```ruby
recurrence = Montrose.every(:week, starts: Date.new(2019, 7, 10), total: 4)
range = Date.new(2019, 9, 1)...Date.new(2019, 9, 8)
recurrence.select { |e| range.include?(e) }
# => []
```
I might consider adding array-like set operators to `Recurrence` to support a third method:
```ruby
recurrence_1 = Montrose.every(:week, starts: Date.new(2019, 7, 10), total: 4)
recurrence_2 = Montrose.daily.between(Date.new(2019, 9, 1)...Date.new(2019, 9, 8))
recurrence_1 & recurrence_2
# => []
```

**Comment by mmagn** [comment]
Thank you, yes I will stick with the ruby filtering way for the moment :)
