### ISSUE TITLE
cannot be serialized in json in Rails

### ISSUE THREAD

**Issue by painforever** [rossta/montrose#127]
I believe it doesn't support JSON. Hopefully can support it in teh futurre

**Comment by rossta** [comment]
I don't understand the issue. Could you please describe how to reproduce the problem you're having?

Recurrence objects are intended to support Rails ActiveRecord-style serialization and the format does happen to be JSON: https://github.com/rossta/montrose/blob/d56d2d94c1f87e14ab225ba50bb8c0494c5d2fed/lib/montrose/recurrence.rb#L243
