### ISSUE TITLE
.every(:week, interval: 2) does not interact with on as expected

### ISSUE THREAD

**Issue by JonPugsley** [rossta/montrose#144]
I've been tinkering with this library and like what I see, though I've either found a bug or don't quite understand the options.

Pattern:
```
Montrose.every(:week, interval: 2).on(["sunday", "monday"]).between(("2021-05-02".to_time)..("2021-05-22".to_time)).events.to_a
```

Events:
```
[2021-05-02, 2021-05-10, 2021-05-16]
```

The matching dates are the sunday of one week, then the monday of the next week, then the sunday of the week after that
![image](https://user-images.githubusercontent.com/29548310/117866907-0e3da600-b26e-11eb-8e53-c4f068be69a1.png)

I would expect the dates to be [2021-05-02, 2021-05-03, 2021-05-16, 2021-05-17]
![image](https://user-images.githubusercontent.com/29548310/117867173-64124e00-b26e-11eb-8433-085625237817.png)

It seems like the library is running a Monday-Sunday week with no option to change this (though Sunday seems to have a day number of 0, which implies a Sunday-Monday week)

**Comment by thewatts** [comment]
Hey @JonPugsley - I just tried that same command into my console, and the results were what you mentioned expecting:

```ruby
Montrose.every(:week, interval: 2).on(["sunday", "monday"]).between(("2021-05-02".to_time)..("2021-05-22".to_time)).events.to_a
```

![image](https://user-images.githubusercontent.com/1141717/130107559-3a851920-4c81-482a-8057-1e935b5eca3b.jpeg)

Are you using the most recent version of the gem?

**Comment by mikalai-yankouski** [comment]
<img width="1772" alt="Screen Shot 2022-04-19 at 15 06 16" src="https://user-images.githubusercontent.com/32986916/163980860-be2722dc-61a6-40e7-869b-42969e01ae32.png">
I have the same behavior

**Comment by cavi21** [comment]
Hi @thewatts I also get the same output as @mikalai-yankouski and @JonPugsley ... 
![Screen Shot 2022-10-20 at 12 53 34](https://user-images.githubusercontent.com/146249/196930024-8247d0df-705f-4a84-b3f5-c64a2b4f819d.png)

the version is the `montrose (0.13.0)`

**Comment by rossta** [comment]
Montrose depends on ActiveSupport for Date/Time calculations. For this recurrence, you'll see different results depending on whether the ActiveSupport `Date.beginning_of_week` setting.

@JonPugsley I suspect Monday is set as the beginning of week in the application where you were testing this recurrence. You could test this on the console: `Date.beginning_of_week`.

You can get the results you are expecting with

```rb
Date.beginning_of_week = :sunday
```

Or in Rails

```rb
# config/application.rb

config.beginning_of_week = :sunday
```

I've added documentation and tests in #164 to further illustrate. Hope that is helpful.
