### ISSUE TITLE
adding a custom label to rule

### ISSUE THREAD

**Issue by flyingboy007** [rossta/montrose#146]
Is it possible to add a custom text field to a rule like below?

`Montrose.r(every: :week, on: [:monday, :wednesday], text: 'custom_label')`
This throws an error. Is there any other way to do this?

**Comment by rossta** [comment]
There is not currently a way to do this. What is the use case?

What about composing this behavior instead? e.g. `events.map { |e| { timestamp: e, text: 'custom_label' }`
