### ISSUE TITLE
29th/30th of each month skips February or uses wrong date for other months

### ISSUE THREAD

**Issue by pareeohnos** [rossta/montrose#171]
I'm trying to figure out how to create a recurrence rule for something that should occur on the 29th or 30th of each month. The 31st is straight forward, as I can set `mday: [-1]` to give me the last day of each month and this correctly adjusts for months with 30 days or February.

The 29th and 30th however are different. If I use just the `mday` option

```
Montrose.r(every: :month, mday: [30]).take(12)
=> [Sun, 30 Jun 2024 10:52:07.000000000 UTC +00:00,
 Tue, 30 Jul 2024 10:52:07.000000000 UTC +00:00,
 Fri, 30 Aug 2024 10:52:07.000000000 UTC +00:00,
 Mon, 30 Sep 2024 10:52:07.000000000 UTC +00:00,
 Wed, 30 Oct 2024 10:52:07.000000000 UTC +00:00,
 Sat, 30 Nov 2024 10:52:07.000000000 UTC +00:00,
 Mon, 30 Dec 2024 10:52:07.000000000 UTC +00:00,
 Thu, 30 Jan 2025 10:52:07.000000000 UTC +00:00,
 Sun, 30 Mar 2025 10:52:07.000000000 UTC +00:00,
 Wed, 30 Apr 2025 10:52:07.000000000 UTC +00:00,
 Fri, 30 May 2025 10:52:07.000000000 UTC +00:00,
 Mon, 30 Jun 2025 10:52:07.000000000 UTC +00:00]
```

It completely skips February, but the rest of the months are fine, and this happens for the 29th as well (except for a leap year). This is of course expected behaviour, however I can't use `[-2]` as the 30th is in the last day for some months, so those months end up with the `29th` instead of the `30th`.

I understand why Montrose skips February if I don't specify the `mday` option, but how can I create a recurring rule for this scenario?

**Comment by rossta** [comment]
I may not fully understand what you’re trying to do, but it sounds like you may need to create a schedule of multiple recurrences. 

For example, to take the 30th day of each month, but during a leap year, the 29th day of February, you will want to create multiple recurrences into a schedule. A schedule interleaves the occurrences:

```ruby
schedule = Montrose::Schedule.build do |s|
  s << { every: :month, mday: [30] }
  s << { every: :month, month: :february, mday: [29] }
end
```


If this isn’t exactly what you want, perhaps it at least gives you an idea of how you can combine recurrences to get the desired behavior.

**Comment by pareeohnos** [comment]
hm yeah I was thinking the schedule was most likely the only real solution here. The issue I've got now is there's a lot of code assuming that the recurrence rule we stored is an instance of `Recurrence` which will now blow up if I switch it.

I'm wondering how challenging it would be (and if you'd be open to a PR) modify the code, so that if the `mday` value provided is higher than the number of days in that month, it returns the last day of the month instead? It could be specified as an additional option to make it backwards compatible as well I suppose

**Comment by pareeohnos** [comment]
I've forked the project and made a small change to check if it would work, I've got the output I was hoping for

```
[4] pry(main)> r = Montrose.r(every: :month, mday: 30)
=> #<Montrose::Recurrence:848 {:every=>:month, :mday=>[30]}>
[5] pry(main)> r.take(12)
=> [2024-06-30 14:14:10 +0100,
 2024-07-30 14:14:10 +0100,
 2024-08-30 14:14:10 +0100,
 2024-09-30 14:14:10 +0100,
 2024-10-30 14:14:10 +0000,
 2024-11-30 14:14:10 +0000,
 2024-12-30 14:14:10 +0000,
 2025-01-30 14:14:10 +0000,
 2025-02-28 14:14:10 +0000,
 2025-03-30 14:14:10 +0100,
 2025-04-30 14:14:10 +0100,
 2025-05-30 14:14:10 +0100]
```

I've got all specs passing as well. I realised in doing this that the current behaviour reflects the behaviour of google calendar (skipping months that don't have that many days) so I've added an option to `skip_months` to toggle the behaviour which defaults to its existing behaviour.

Would you be interested in a PR for this?

**Comment by pareeohnos** [comment]
@rossta happy to change the configuration to something along those lines, although that looks slightly different to what I'm looking at right now. I'm not looking so much at specifying the exact days for specific months, but instead having months with fewer days than the number you've specified use the last day of the month.

So for example, if I specify that I want the 31st, then right now it would exclude every month with 30 days. Instead what I need is a way of still including those months, but making them use the 30th instead if that makes sense? What about something like

```ruby
Montrose.every(:month, mday: [1, -1]) # Supports existing API
Montrose.every(:month, mday: { default: [1, 31], february: 28 })
Montrose.every(:month, mday: { default: 15, [:march, :april, :may]: 14 })
Montrose.every(:month, mday: { default: 30, else: -1 }
```

I don't like `else` as an option name but it shows the idea, that if the default day doesn't exist then use that as an alternative

**Comment by pareeohnos** [comment]
I've opened a PR for this. I've gone with `fallback` instead of `else` as I think it's a little clearer, but I'm open to changes
