### ISSUE TITLE
Can't figure out how/when to use this gem

### ISSUE THREAD

**Issue by PikachuEXE** [rossta/montrose#35]
As title

I use cron for my Ruby + non-Ruby recurring tasks

**Comment by rossta** [comment]
Yes, you should use cron for recurring jobs is your system. Montrose wouldn't be a good fit for that. It may be useful for modeling recurring concepts within an application, e.g., like a user of website creating a recurring events on a calendar, and giving you a way to store that concept in a database. Does that help?

**Comment by PikachuEXE** [comment]
OK I guess I don't need this gem for now :P 
But thanks for writing it :smile:
