### ISSUE TITLE
Support for "locking" TimeZone

### ISSUE THREAD

**Issue by rossta** [rossta/montrose#65]
As noted in #62, if serializing a recurrence in one time zone context and deserializing it in another, the recurrence events may be inconsistent if comparing those two instances. We may be able to add a `:time_zone` option that will set the recurrence's timezone so deserialization will be enforced. May require further investigation.

**Comment by yoonwaiyan** [comment]
Would like to have this supported too, my current solution on dealing is using the time zone block as mentioned in issue #62 .

**Comment by rossta** [comment]
I'm going to close this issue for now as I believe the Time zone block is the right way to go for most applications; adding a separate mechanism for realizing time zones in the gem may lead to bugs or unexpected cases when used along with the global Time zone setting.
