### ISSUE TITLE
Passing seconds to at

### ISSUE THREAD

**Issue by terencedignon** [rossta/montrose#94]
As far as I can tell _at_ only reads hours and minutes.  Is there a way to include seconds? It's an important data point in our schedules.

### Desired Behavior

```
[57] pry(main)> Montrose.weekly.at('23:59:59')
=> #<Montrose::Recurrence:3fd4d7a04588 {:every=>:week, :at=>[[23, 59, 59]]}>
```

### Actual Behavior

```
[57] pry(main)> Montrose.weekly.at('23:59:59')
=> #<Montrose::Recurrence:3fd4d7a04588 {:every=>:week, :at=>[[23, 59]]}>

**Comment by rossta** [comment]
Thanks. Could you whether #95 accounts for your use case?

**Comment by terencedignon** [comment]
That looks great! Thank you.
